//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCat()
        {
            this.tblProes = new HashSet<tblPro>();
        }
    
        public int CatID { get; set; }
        public string CatName { get; set; }
        public Nullable<int> CatStatus { get; set; }
        public string CatDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPro> tblProes { get; set; }
    }
}
